version: "1.0"
services:
  api:
    build: backend/api
    ports:
      - "8080:8080"

    environment:
      - SECRET_KEY=${DJANGO_TOKEN}
      - INFLUXDB_TOKEN=${INFLUX_TOKEN}
      - INFLUXDB_ORG=${INFLUX_ORG}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}

    depends_on:
      - influxdb
      - emqx

    networks:
      - internal_network

  influxdb:
    image: "influxdb:latest"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    ports:
      - "8086:8086"

    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PSW}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

    networks:
      - internal_network

  emqx:
    image: "emqx:latest"
    ports:
      - "18083:18083"
      - "1883:1883"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

    networks:
      - internal_network

volumes:
  influxdb-storage:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log:


networks:
  internal_network:
    driver: bridge
