# Generated by Django 4.1.3 on 2022-11-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Silos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heigth', models.FloatField()),
                ('diameter', models.FloatField()),
                ('action', models.ManyToManyField(blank=True, to='api.actions')),
                ('liquid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.liquids')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zones')),
            ],
        ),
    ]
