# Generated by Django 4.1.3 on 2022-11-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actions_silos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silos',
            old_name='action',
            new_name='actions',
        ),
    ]
