# Generated by Django 4.1.3 on 2022-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_action_silos_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='liquids',
            options={'verbose_name_plural': 'Liquids'},
        ),
        migrations.AlterModelOptions(
            name='silos',
            options={'verbose_name_plural': 'Silos'},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name_plural': 'Zone'},
        ),
        migrations.RenameField(
            model_name='silos',
            old_name='heigth',
            new_name='height',
        ),
    ]
