# Generated by Django 4.1.3 on 2022-11-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_actions_options_alter_liquids_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.RemoveField(
            model_name='silos',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='silos',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='Zones',
        ),
        migrations.AddField(
            model_name='logs',
            name='silos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.silos'),
        ),
    ]
