# Generated by Django 4.1.3 on 2022-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logs_remove_silos_actions_remove_silos_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
