# Generated by Django 4.1.3 on 2022-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_logs_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'get_latest_by': '-time', 'ordering': ['-time'], 'verbose_name_plural': 'Logs'},
        ),
        migrations.AddField(
            model_name='liquids',
            name='cO2Max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='cO2Min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='maxPression',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='minPression',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='pHMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='pHMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='tempMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquids',
            name='tempMin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silos',
            name='name',
            field=models.CharField(default='Silos#1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liquids',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
