# Generated by Django 4.1.3 on 2022-12-02 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_silos_liquid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquids',
            name='cO2Max',
            field=models.FloatField(blank=True, help_text='% CO2', null=True),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='cO2Min',
            field=models.FloatField(blank=True, help_text='% CO2', null=True),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='pHMax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(13.0)]),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='pHMin',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(13.0)]),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='tempMax',
            field=models.FloatField(blank=True, help_text='°C', null=True),
        ),
        migrations.AlterField(
            model_name='liquids',
            name='tempMin',
            field=models.FloatField(blank=True, help_text='°C', null=True),
        ),
    ]
