# Generated by Django 4.1.3 on 2022-12-02 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_liquids_co2max_alter_liquids_co2min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquids',
            name='pHMax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(13.0)]))]),
        ),
    ]
