# Generated by Django 4.1.3 on 2022-12-02 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_liquids_phmax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquids',
            name='pHMax',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
