# Generated by Django 4.1.3 on 2022-12-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_liquids_phmax'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(max_length=255)),
                ('maintenance_interval', models.IntegerField(help_text='days')),
                ('min_value', models.FloatField(help_text='(SI)')),
                ('max_value', models.FloatField(help_text='(SI)')),
            ],
            options={
                'verbose_name_plural': 'Sensors Types',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('diameter', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.RemoveField(
            model_name='silos',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='silos',
            name='height',
        ),
        migrations.CreateModel(
            name='SensorsInSilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_maintenance', models.DateTimeField()),
                ('position', models.CharField(max_length=255)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensorstypes')),
                ('silos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.silos')),
            ],
        ),
        migrations.AddField(
            model_name='silos',
            name='sensors',
            field=models.ManyToManyField(through='api.SensorsInSilos', to='api.sensorstypes'),
        ),
        migrations.AddField(
            model_name='silos',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sizes'),
        ),
    ]
