# Generated by Django 4.2.1 on 2023-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sensorstypes_sizes_remove_silos_diameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorsinsilos',
            options={'verbose_name_plural': 'Sensors In Silos'},
        ),
        migrations.AddField(
            model_name='silos',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='silos',
            name='sensors',
            field=models.ManyToManyField(blank=True, through='api.SensorsInSilos', to='api.sensorstypes'),
        ),
    ]
