# Generated by Django 4.2.1 on 2023-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sensorsinsilos_options_silos_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorstypes',
            name='sensor_slug',
            field=models.CharField(default='temp_sensor', max_length=255),
            preserve_default=False,
        ),
    ]
