# Generated by Django 4.2.1 on 2023-05-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sensorstypes_sensor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='cO2Max',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='cO2Min',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='maxPression',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='minPression',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='pHMax',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='pHMin',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='tempMax',
        ),
        migrations.RemoveField(
            model_name='liquids',
            name='tempMin',
        ),
        migrations.CreateModel(
            name='LiquidProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.properties')),
            ],
            options={
                'verbose_name_plural': 'Liquid Properties',
            },
        ),
        migrations.AddField(
            model_name='liquids',
            name='properties',
            field=models.ManyToManyField(blank=True, to='api.liquidproperties'),
        ),
    ]
