# Generated by Django 4.2.1 on 2023-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_properties_remove_liquids_co2max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='tare',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
