# Generated by Django 4.2.1 on 2023-05-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sizes_tare'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Measure Units',
            },
        ),
        migrations.CreateModel(
            name='SensorsTypology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('sensor_slug', models.CharField(max_length=255)),
                ('maintenance_interval', models.IntegerField(help_text='days')),
                ('min_value', models.FloatField(help_text='(SI)')),
                ('max_value', models.FloatField(help_text='(SI)')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.measureunits')),
            ],
            options={
                'verbose_name_plural': 'Sensors Topologies',
            },
        ),
        migrations.AlterField(
            model_name='sensorsinsilos',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensorstypology'),
        ),
        migrations.AlterField(
            model_name='silos',
            name='sensors',
            field=models.ManyToManyField(blank=True, through='api.SensorsInSilos', to='api.sensorstypology'),
        ),
        migrations.DeleteModel(
            name='SensorsTypes',
        ),
    ]
