# Generated by Django 4.2.1 on 2023-05-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_measureunits_sensorstypology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sensors Types',
            },
        ),
        migrations.AddField(
            model_name='sensorstypology',
            name='sensor_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.sensorstypes'),
            preserve_default=False,
        ),
    ]
